// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dplwujqblzihwystlbov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwbHd1anFibHppaHd5c3RsYm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzU0NjQsImV4cCI6MjA2MjgxMTQ2NH0.lFz2UzWIM2OUrozgno1mchz-_Rag17r_YYz2NTl7ppg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);